services:
  app:
    build:
      context: ../..
      dockerfile: .devcontainer/docker/Dockerfile
    image: &project_name MY-COOL-GEM
    container_name: *project_name
    env_file: ../config/.env
    environment:
      - RAILS_ENV=development
      - RUBOCOP_OPTS="--config /app/.devcontainer/config/.rubocop.yml"
      - SOLARGRAPH_GLOBAL_CONFIG=/app/.devcontainer/config/.solargraph.yml
      - SOLARGRAPH_CACHE=/root/.cache/solargraph
    volumes:
      - ../..:/app
      - ${HOME}/.cache/solargraph:/root/.cache/solargraph # mount local solargraph cache
      - ${HOME}/.cache/yard/bundle_docs:/usr/local/bundle/doc # mount local yard docs cache for bundle gems
      - ${HOME}/.cache/yard/stdlib_docs:/usr/local/lib/ruby/gems/2.6.0/doc # mount local yard docs cache for Ruby 2.6.x stdlib gems
