# Configuration file for the Solargraph Ruby language server.
# Sets up code completion, analysis, and linting for this project.
# Adds support for Ruby and Ruby on Rails IDE IntelliSense features.
---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-rails
max_files: 5000
