services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: &project_name my-cool-gem # TODO: CHANGE THIS TO YOUR GEM NAME
    container_name: *project_name
    env_file: .env
    environment:
      - SOLARGRAPH_GLOBAL_CONFIG=/root/.config/solargraph/config.yml
      - SOLARGRAPH_CACHE=/root/.cache/solargraph
    volumes:
       - ..:/app
       - /app/pkg # don't mount the pkg directory, it will be created by the build
       - ${HOME}/.config:/root/.config # mount local config, specifically for solargraph
       - ${HOME}/.cache:/root/.cache # mount local cache, specifically for solargraph
    command: ["tail", "-f", "/dev/null"]
