# STAGE 1: Initial setup
FROM ruby:2.6.10 as base
WORKDIR /app

# Install missing package(s)
RUN apt-get update -qq && apt-get install -yq --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Prep for gem installation
# NOTE: The RubyGems version that comes with Ruby 2.6 contains a bug and must be updated to v3.2.3.
#       Also, Bundler must be pinned to v2.4.22 because it is the last version that works with Ruby 2.6.
#       When Ruby gets upgraded, the pinned versions can get removed below.
RUN gem update --system 3.2.3 && gem install bundler -v 2.4.22

# STAGE 2: Install development & runtime gems
# NOTE: Copy *only* the files you absolutely need for this stage, otherwise caching will become useless
FROM base as gems
COPY Gemfile Gemfile.lock ../*.gemspec ./
COPY lib/path/to/version.rb lib/path/to/version.rb
RUN bundle update --bundler && bundle install

# STAGE 3: Install your gem & copy over cached gems
FROM base as final
COPY --from=gems /usr/local/bundle /usr/local/bundle
COPY .. /app

# Install the gem CLI
RUN bundle exec rake install
# Alternatively, you can run:
# RUN gem build *.gemspec && gem install *.gem

# Keep container running
CMD ["tail", "-f", "/dev/null"]
